### ISSUE TITLE
Contribute button active after the jam is closed

### ISSUE THREAD

**Issue by riseandshaheen** [riseandshaheen/jam-twt#3]
## Steps to reproduce
1. Create a jam of 3 entries
2. Fill all entries. It gets closed and the `Contribute` button gets disabled after the third entry as expected.
3. Connect with 4th account and the `Contribute` button gets enabled again. Screenshot below 
<img width="1301" alt="Screenshot 2024-06-14 at 2 34 54 PM" src="https://github.com/riseandshaheen/jam-twt/assets/91434451/bcb558a8-7122-4977-97f7-b73867ba50c4">

**Comment by brunomenezes** [comment]
Fixed on d65e465245926d88a20a77c8fbb01f96788f8539
