### ISSUE TITLE
Withdraw amount format

### ISSUE THREAD

**Issue by brunomenezes** [riseandshaheen/jam-twt#5]
When submitting the amount to withdraw, I parse the amount using the ethereum decimals (18),  the same way I do for `minting`, so the payload would look like this before becoming a `hexstring`.

```json
{"action":"eth.withdraw","amount":"3166666666666666670"}
```
But that causes issues in the backend handler and fails. Looking at the code, I noticed it was expecting the `number` format e.g. 

```json

{ action: "eth.withdraw", amount: "3.16666666666666667" }
```

<details>
<summary><h3> Failed logs</h3></summary>

validator-1                 | 2024-06-15T04:05:46.969 INF INFO dispatcher::machine::rollups_broker: producing input event event=RollupsInput { parent_id: "1718423686915-0", epoch_index: 15, inputs_sent_count: 30, data: AdvanceStateInput(RollupsAdvanceStateInput { metadata: InputMetadata { msg_sender: f39fd6e51aad88f6f4ce6ab8827279cfffb92266, block_number: 26510, timestamp: 1718424346, epoch_index: 0, input_index: 29 }, payload: eyJhY3Rpb24iOiJldGgud2l0aGRyYXciLCJhbW91bnQiOiIzMTY2NjY2NjY2NjY2NjY2NjcwIn0=, tx_hash: 500148c65d73a19265780badb16d74d963167ed260bf17f9b93598b290947209 }) } service=dispatcher
validator-1                 | 2024-06-15T04:05:46.970 INF INFO indexer::indexer: received event event=Input(Event { id: "1718424346969-0", payload: RollupsInput { parent_id: "1718423686915-0", epoch_index: 15, inputs_sent_count: 30, data: AdvanceStateInput(RollupsAdvanceStateInput { metadata: InputMetadata { msg_sender: f39fd6e51aad88f6f4ce6ab8827279cfffb92266, block_number: 26510, timestamp: 1718424346, epoch_index: 0, input_index: 29 }, payload: eyJhY3Rpb24iOiJldGgud2l0aGRyYXciLCJhbW91bnQiOiIzMTY2NjY2NjY2NjY2NjY2NjcwIn0=, tx_hash: 500148c65d73a19265780badb16d74d963167ed260bf17f9b93598b290947209 }) } }) service=indexer
validator-1                 | 2024-06-15T04:05:46.970 INF INFO advance_runner::runner: consumed input event event=RollupsInput { parent_id: "1718423686915-0", epoch_index: 15, inputs_sent_count: 30, data: AdvanceStateInput(RollupsAdvanceStateInput { metadata: InputMetadata { msg_sender: f39fd6e51aad88f6f4ce6ab8827279cfffb92266, block_number: 26510, timestamp: 1718424346, epoch_index: 0, input_index: 29 }, payload: eyJhY3Rpb24iOiJldGgud2l0aGRyYXciLCJhbW91bnQiOiIzMTY2NjY2NjY2NjY2NjY2NjcwIn0=, tx_hash: 500148c65d73a19265780badb16d74d963167ed260bf17f9b93598b290947209 }) } service=advance-runner
validator-1                 | 2024-06-15T04:05:46.978 INF INFO indexer::indexer: waiting for next event self.state=IndexerState { inputs_last_id: "1718424346969-0", outputs_last_id: "1718423686920-1", inputs_stream: RollupsInputsStream { key: "{chain-31337:dapp-ab7528bb862fb57e8a2bcd567a2e929a0be56a5e}:rollups-inputs" }, outputs_stream: RollupsOutputsStream { key: "{chain-31337:dapp-ab7528bb862fb57e8a2bcd567a2e929a0be56a5e}:rollups-outputs" } } service=indexer
validator-1                 | 2024-06-15T04:05:46.993 INF [INFO  rollup_http_server::http_service] Received new request of type ADVANCE service=server-manager
validator-1                 | 2024-06-15T04:05:46.994 INF [INFO  actix_web::middleware::logger] 127.0.0.1 "POST /finish HTTP/1.1" 200 316 "-" "undici" 0.001024 service=server-manager
validator-1                 | 2024-06-15T04:05:47.012 INF Advance payload :  {"action":"eth.withdraw","amount":"3166666666666666670"} service=server-manager
validator-1                 | 2024-06-15T04:05:47.013 INF Request: Withdraw ether service=server-manager
validator-1                 | 2024-06-15T04:05:47.035 ERR Error while withdrawing ether:  Error: insufficient balance of user 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266: 3166666666666666670000000000000000000 > 3166666666666666670 service=server-manager
validator-1                 | 2024-06-15T04:05:47.035 INF at WalletAppImpl.withdrawEther (/opt/cartesi/dapp/index.js:26782:17) service=server-manager
validator-1                 | 2024-06-15T04:05:47.036 INF at /opt/cartesi/dapp/index.js:28569:30 service=server-manager
validator-1                 | 2024-06-15T04:05:47.036 INF at HttpApp.handleAdvance (/opt/cartesi/dapp/index.js:2164:34) service=server-manager
validator-1                 | 2024-06-15T04:05:47.036 INF at HttpApp.start (/opt/cartesi/dapp/index.js:2203:37) service=server-manager
validator-1                 | 2024-06-15T04:05:47.036 INF     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) service=server-manager
validator-1                 | 2024-06-15T04:05:47.980 INF INFO advance_runner::runner: waiting for the next input event service=advance-runner
validator-1                 | 2024-06-15T04:05:47.980 INF INFO indexer::indexer: received event event=Output(Event { id: "1718424347980-0", payload: AdvanceResult(RollupsAdvanceResult { input_index: 29, status: Accepted }) }) service=indexer
validator-1                 | 2024-06-15T04:05:47.986 INF INFO indexer::indexer: waiting for next event self.state=IndexerState { inputs_last_id: "1718424346969-0", outputs_last_id: "1718424347980-0", inputs_stream: RollupsInputsStream { key: "{chain-31337:dapp-ab7528bb862fb57e8a2bcd567a2e929a0be56a5e}:rollups-inputs" }, outputs_stream: RollupsOutputsStream { key: "{chain-31337:dapp-ab7528bb862fb57e8a2bcd567a2e929a0be56a5e}:rollups-outputs" } } service=indexer

validator-1                 | 2024-06-15T04:06:06.290 INF [INFO  rollup_http_server::http_service] Received new request of type INSPECT service=server-manager
validator-1                 | 2024-06-15T04:06:06.292 INF [INFO  actix_web::middleware::logger] 127.0.0.1 "POST /finish HTTP/1.1" 200 156 "-" "undici" 0.000960 service=server-manager
validator-1                 | 2024-06-15T04:06:06.356 INF Received inspect request payload :  balance/0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 service=server-manager
validator-1                 | 2024-06-15T04:06:06.358 INF eth balance: 3166666666666666670n service=server-manager
validator-1                 | 2024-06-15T04:06:06.389 INF [INFO  actix_web::middleware::logger] 127.0.0.1 "POST /report HTTP/1.1" 202 0 "-" "undici" 0.000448 service=server-manager

</details>

<details>
<summary><h3>Logs for success handling</h3></summary>

validator-1                 | 2024-06-15T04:18:06.971 INF INFO dispatcher::machine::rollups_broker: producing input event event=RollupsInput { parent_id: "1718424346969-0", epoch_index: 15, inputs_sent_count: 31, data: AdvanceStateInput(RollupsAdvanceStateInput { metadata: InputMetadata { msg_sender: f39fd6e51aad88f6f4ce6ab8827279cfffb92266, block_number: 26658, timestamp: 1718425086, epoch_index: 0, input_index: 30 }, payload: eyJhY3Rpb24iOiJldGgud2l0aGRyYXciLCJhbW91bnQiOiIzLjE2NjY2NjY2NjY2NjY2NjY3In0=, tx_hash: e640c9226f5db6fbe1283d0b6ec07a001d2a6c84aae61253cf51f7825585c7cf }) } service=dispatcher
validator-1                 | 2024-06-15T04:18:06.971 INF INFO advance_runner::runner: consumed input event event=RollupsInput { parent_id: "1718424346969-0", epoch_index: 15, inputs_sent_count: 31, data: AdvanceStateInput(RollupsAdvanceStateInput { metadata: InputMetadata { msg_sender: f39fd6e51aad88f6f4ce6ab8827279cfffb92266, block_number: 26658, timestamp: 1718425086, epoch_index: 0, input_index: 30 }, payload: eyJhY3Rpb24iOiJldGgud2l0aGRyYXciLCJhbW91bnQiOiIzLjE2NjY2NjY2NjY2NjY2NjY3In0=, tx_hash: e640c9226f5db6fbe1283d0b6ec07a001d2a6c84aae61253cf51f7825585c7cf }) } service=advance-runner
validator-1                 | 2024-06-15T04:18:06.971 INF INFO indexer::indexer: received event event=Input(Event { id: "1718425086971-0", payload: RollupsInput { parent_id: "1718424346969-0", epoch_index: 15, inputs_sent_count: 31, data: AdvanceStateInput(RollupsAdvanceStateInput { metadata: InputMetadata { msg_sender: f39fd6e51aad88f6f4ce6ab8827279cfffb92266, block_number: 26658, timestamp: 1718425086, epoch_index: 0, input_index: 30 }, payload: eyJhY3Rpb24iOiJldGgud2l0aGRyYXciLCJhbW91bnQiOiIzLjE2NjY2NjY2NjY2NjY2NjY3In0=, tx_hash: e640c9226f5db6fbe1283d0b6ec07a001d2a6c84aae61253cf51f7825585c7cf }) } }) service=indexer
validator-1                 | 2024-06-15T04:18:06.977 INF INFO indexer::indexer: waiting for next event self.state=IndexerState { inputs_last_id: "1718425086971-0", outputs_last_id: "1718424347980-0", inputs_stream: RollupsInputsStream { key: "{chain-31337:dapp-ab7528bb862fb57e8a2bcd567a2e929a0be56a5e}:rollups-inputs" }, outputs_stream: RollupsOutputsStream { key: "{chain-31337:dapp-ab7528bb862fb57e8a2bcd567a2e929a0be56a5e}:rollups-outputs" } } service=indexer
validator-1                 | 2024-06-15T04:18:06.983 INF [INFO  rollup_http_server::http_service] Received new request of type ADVANCE service=server-manager
validator-1                 | 2024-06-15T04:18:06.984 INF [INFO  actix_web::middleware::logger] 127.0.0.1 "POST /finish HTTP/1.1" 200 316 "-" "undici" 0.001088 service=server-manager
validator-1                 | 2024-06-15T04:18:07.020 INF Advance payload :  {"action":"eth.withdraw","amount":"3.16666666666666667"} service=server-manager
validator-1                 | 2024-06-15T04:18:07.021 INF Request: Withdraw ether service=server-manager
validator-1                 | 2024-06-15T04:18:07.110 INF [INFO  actix_web::middleware::logger] 127.0.0.1 "POST /voucher HTTP/1.1" 201 11 "-" "undici" 0.000768 service=server-manager
anvil-1                     | eth_blockNumber
anvil-1                     | eth_getBlockByNumber
anvil-1                     | eth_getLogs
squid_processor-1           | {"level":2,"time":1718425087756,"ns":"sqd:processor:mapping","msg":"0xab7528bb862fb57e8a2bcd567a2e929a0be56a5e-30 (Input) stored"}
squid_processor-1           | {"level":2,"time":1718425087756,"ns":"sqd:processor:mapping","msg":"Flushing 1 entities: tokens: 0, applications: 0, factories: 0, deposits: 0, inputs: 1, nfts: 0, erc721Deposits: 0, multiTokens: 0, erc1155Deposits: 0"}
squid_processor-1           | {"level":2,"time":1718425087763,"ns":"sqd:processor","msg":"26658 / 26658, rate: 0 blocks/sec, mapping: 124 blocks/sec, 149 items/sec, eta: 0s"}
validator-1                 | 2024-06-15T04:18:07.978 INF INFO indexer::indexer: received event event=Output(Event { id: "1718425087978-0", payload: AdvanceResult(RollupsAdvanceResult { input_index: 30, status: Accepted }) }) service=indexer
validator-1                 | 2024-06-15T04:18:07.978 INF INFO advance_runner::runner: waiting for the next input event service=advance-runner
validator-1                 | 2024-06-15T04:18:07.982 INF INFO indexer::indexer: waiting for next event self.state=IndexerState { inputs_last_id: "1718425086971-0", outputs_last_id: "1718425087978-0", inputs_stream: RollupsInputsStream { key: "{chain-31337:dapp-ab7528bb862fb57e8a2bcd567a2e929a0be56a5e}:rollups-inputs" }, outputs_stream: RollupsOutputsStream { key: "{chain-31337:dapp-ab7528bb862fb57e8a2bcd567a2e929a0be56a5e}:rollups-outputs" } } service=indexer
validator-1                 | 2024-06-15T04:18:07.982 INF INFO indexer::indexer: received event event=Output(Event { id: "1718425087978-1", payload: Voucher(RollupsVoucher { index: 0, input_index: 30, destination: ab7528bb862fb57e8a2bcd567a2e929a0be56a5e, payload: Ui9oFQAAAAAAAAAAAAAAAPOf1uUarYj29M5quIJyec//uSJmAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAK/JCjjy8qq4= }) }) service=indexer
validator-1                 | 2024-06-15T04:18:07.985 INF INFO indexer::indexer: waiting for next event self.state=IndexerState { inputs_last_id: "1718425086971-0", outputs_last_id: "1718425087978-1", inputs_stream: RollupsInputsStream { key: "{chain-31337:dapp-ab7528bb862fb57e8a2bcd567a2e929a0be56a5e}:rollups-inputs" }, outputs_stream: RollupsOutputsStream { key: "{chain-31337:dapp-ab7528bb862fb57e8a2bcd567a2e929a0be56a5e}:rollups-outputs" } } service=indexer
anvil-1                     | eth_blockNumber
anvil-1                     | eth_getTransactionReceipt
validator-1                 | 2024-06-15T04:18:08.263 INF [INFO  rollup_http_server::http_service] Received new request of type INSPECT service=server-manager
validator-1                 | 2024-06-15T04:18:08.264 INF [INFO  actix_web::middleware::logger] 127.0.0.1 "POST /finish HTTP/1.1" 200 156 "-" "undici" 0.000896 service=server-manager
validator-1                 | 2024-06-15T04:18:08.327 INF Received inspect request payload :  balance/0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 service=server-manager
validator-1                 | 2024-06-15T04:18:08.328 INF eth balance: 0n service=server-manager
validator-1                 | 2024-06-15T04:18:08.359 INF [INFO  actix_web::middleware::logger] 127.0.0.1 "POST /report HTTP/1.1" 202 0 "-" "undici" 0.000448 service=server-manager
anvil-1                     | eth_blockNumber
 
</details>

**Comment by riseandshaheen** [comment]
You're right, it's better to keep the amount string Wei format(10^18) as the Deroll library accepts the same. I've added a fix [here](https://github.com/riseandshaheen/jam-twt/commit/6f0a6a8e447bc6475dd73f69d0dcc562b80b8467)
